#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

name: Build Codebase

on:
  push:
    branches: [master, 'feature/*', 'bugfix/*', 'hotfix/*', 'release/*']     
  pull_request:
    types: [opened, edited, reopened, converted_to_draft, ready_for_review, synchronize]
    branches: [master]

jobs:
    deploy-prep:
        name: Analyze Test & Build Codebase
        runs-on: ubuntu-latest
        steps:

            - name: Setup Node JS
              uses: actions/setup-node@v3
              with:
                node-version: '18.x'      

            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Install dependencies
              run: npm install --silent

            - name: Run Stylelint
              #env:
                # LINTER_RULES_PATH: .github/linters/.stylelintrc.json
              run: npx stylelint --quiet "**/*.css" --config .github/linters/.stylelintrc.json

            - name: Run build and test
              run: |        
                npm run build --if-present
                npm run test --if-present
    
    deploy-dev:
      name: Deploy to Dev
      needs: [deploy-prep]
      runs-on: ubuntu-latest
      environment:
        name: dev
        url: 'https://dev.example.com'
      steps:
        - name: Print Environment Variables & Secrets
          run: |
            echo deploying to dev...

    deploy-qa:
      name: Deploy to QA
      needs: [deploy-prep, deploy-dev]
      runs-on: ubuntu-latest
      environment:
        name: qa
        url: 'https://qa.example.com'
      steps:
        - name: Print Environment Variables & Secrets
          run: |
            echo deploying to qa...

    publish-package:
      name: Publish Package
      needs: [deploy-prep, deploy-dev, deploy-qa]
      runs-on: ubuntu-latest
      if: (github.ref == 'refs/heads/main')
      environment:
        name: prod
        url: 'https://www.example.com'
      steps:
        - name: Print Environment Variables & Secrets
          run: |
            echo publishing package...