---
#################################
#################################
## Super Linter GitHub Actions ##
#################################
#################################
name: Build Codebase

#
# Documentation:
# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches:
        - 'feature/*'
        - 'bugfix/*'
        - 'hotfix/*'
        - 'release/*'
        - 'main'
        - 'master'
  pull_request:
    branches:
      - master

jobs:
    super-linter:
        name: Lint Codebase
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v4
      
            - name: Lint Code Base
              uses: super-linter/super-linter@v5
              env:
                VALIDATE_ALL_CODEBASE: false
                DEFAULT_BRANCH: main
                #LINTER_RULES_PATH: /
                #CSS_FILE_NAME: .stylelintrc.json
                #JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
                VALIDATE_CSS: true
                #VALIDATE_JAVASCRIPT_ES: true
    